baseURL = "/"
languageCode = "en-us"
title = "aleksnyder.net"

[taxonomies]
  tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[module]
  [[module.mounts]]
    disableWatch = true
    source = 'works'
    target = 'assets'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
