baseURL = "/"
languageCode = "en-us"
title = "aleksnyder.net"

[taxonomies]
  tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[module]
  [[module.mounts]]
    source = 'works'
    target = 'works'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
