name: deploy aleksnyder.net
on:
  push:
    branches:
      - ci/deploy-docker-action
  
runs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/aleksnyder/ci:latest
          docker push ghcr.io/aleksnyder/ci:latest
  #runs-on: ubuntu-latest
  
  #steps:
  #- name: install ssh keys
    # check this thread to understand why its needed:
    # https://stackoverflow.com/a/70447517
  #  run: |
  #    install -m 600 -D /dev/null ~/.ssh/id_rsa
  #    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  #    ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
  #- name: connect and pull
  #  run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.#WORK_DIR }} && git checkout main && git pull && hugo && exit"
  #- name: cleanup
  #  run: rm -rf ~/.ssh